services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4597:4566-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,dynamodb,apigateway,cloudformation,logs,iam,s3,ssm
      - DEBUG=1
#      - SERVICES=${SERVICES- }
#      - DEBUG=${DEBUG- }
#      - DATA_DIR=${DATA_DIR- }
#      - PORT_WEB_UI=${PORT_WEB_UI- }
#      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
#      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - DB_HOST=localhost
#      - DB_PORT=3306
#      - DB_USER=root
#      - DB_PASS=
#      - DB_DATABASE=swapi_indra
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

networks:
  localstack:
    external: false
    driver: bridge
    name: localstack